sudo: required

services:
    - docker

before_install:
    - make docker-build

script:
    - make docker-test

after_script:
  - test $TRAVIS_BRANCH != 'master' && make trigger-build PROJECT=home:eliostvs:test TOKEN=$(OBS_TOKEN)

notifications:
    email:
        on_success: change
        on_failure: always
